image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy

unit_test-job:
  stage: test
  script:
    - groupadd -g 900 ci
    - useradd -d /builds -s /bin/bash -M -u 900 -g 900 -N ci
    - chown -R ci:ci /builds
    - su ci -c "mvn test -U"

build-job:
  stage: build
  script:
    - groupadd -g 900 ci
    - useradd -d /builds -s /bin/bash -M -u 900 -g 900 -N ci
    - chown -R ci:ci /builds
    - su ci -c "mvn package -U -DskipTests=true"
    - mv webapp/target/openmrs.war webapp/target/lh-toolkit.war
    #Delete first, then upload and publish
    - curl -X DELETE -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/librehealth/lh-toolkit-war/lh-toolkit.war
    - curl -T webapp/target/lh-toolkit.war -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/librehealth/lh-toolkit-war/lh-toolkit-devbuilds/latest/lh-toolkit.war
    - curl -X POST -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/librehealth/lh-toolkit-war/lh-toolkit-devbuilds/latest/publish

  artifacts:
    paths:
      - webapp/target/*.war
    expire_in: 5 days

deploy-job:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y && apt-get install rsync -y
    # run ssh-agent
    - eval $(ssh-agent -s)
    - mv webapp/target/lh-toolkit.war webapp/target/master.war
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress webapp/target/master.war ci@toolkit.librehealth.io:/var/lib/tomcat8/webapps
