image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy
  
unit_test-job:
  stage: test
  script: "mvn test -U"
  
build-job:
  stage: build
  script:
    - mvn package -U -DskipTests=true
    - mv webapp/target/openmrs.war webapp/target/lh-toolkit.war
    #Delete first, then upload and publish
    - curl -X DELETE -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/librehealth/lh-toolkit-war/1.12.x.war
    - curl -T webapp/target/lh-toolkit.war -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/librehealth/lh-toolkit-war/lh-toolkit-devbuilds/1.12.x/1.12.x.war
    - curl -X POST -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/librehealth/lh-toolkit-war/lh-toolkit-devbuilds/1.12.x/publish
    
  artifacts:
    paths:
      - webapp/target/*.war
    expire_in: 5 days
    
deploy-job:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y && apt-get install rsync -y
    # run ssh-agent
    - eval $(ssh-agent -s)
    - mv webapp/target/lh-toolkit.war webapp/target/1.12.x.war
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress webapp/target/1.12.x.war ci@toolkit.librehealth.io:/var/lib/tomcat8/webapps